# Generated by Django 4.2.7 on 2023-11-04 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.FloatField()),
                ('badges', models.ManyToManyField(to='task_management.taskbadge')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('priority', models.BigIntegerField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.taskoption')),
            ],
        ),
    ]
