# Generated by Django 4.2.7 on 2023-11-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskoption',
            name='badges',
            field=models.ManyToManyField(blank=True, null=True, to='task_management.taskbadge'),
        ),
    ]
