# Generated by Django 4.2.7 on 2023-11-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_alter_task_end_alter_task_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskbadge',
            name='colour',
            field=models.TextField(default='CFF4FC'),
        ),
    ]
