# Generated by Django 4.2.7 on 2023-11-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_taskbadge_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskbadge',
            name='colour',
        ),
        migrations.AddField(
            model_name='taskbadge',
            name='background_colour',
            field=models.TextField(default='#CFF4FC'),
        ),
        migrations.AddField(
            model_name='taskbadge',
            name='text_colour',
            field=models.TextField(default='#055160'),
        ),
    ]
