# Generated by Django 4.2.7 on 2023-11-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0004_remove_taskbadge_colour_taskbadge_background_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.BigIntegerField(default=1),
        ),
    ]
